In [45]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv('tech-purchase.csv')
df.head(10)

SyntaxError: invalid syntax (3726807395.py, line 4)

In [21]:
#a)more complicated info about NULL VALUES in dataframe
null_values = df.isnull().sum()
null_values

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [22]:
#total result among whole DataFrame
null_values.sum()

3270

In [33]:
#b)DROP
drop_null = df.dropna()
drop_null.head(15)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"
10,176566,Wired Headphones,1,11.99,04/08/19 14:05,"83 7th St, Boston, MA 02215"
11,176567,Google Phone,1,600,04/18/19 17:18,"444 7th St, Los Angeles, CA 90001"
12,176568,Lightning Charging Cable,1,14.95,04/15/19 12:18,"438 Elm St, Seattle, WA 98101"
13,176569,27in 4K Gaming Monitor,1,389.99,04/16/19 19:23,"657 Hill St, Dallas, TX 75001"
14,176570,AA Batteries (4-pack),1,3.84,04/22/19 15:09,"186 12th St, Dallas, TX 75001"
15,176571,Lightning Charging Cable,1,14.95,04/19/19 14:29,"253 Johnson St, Atlanta, GA 30301"

In [49]:
    #2-TASK
# df['Month'] = pd.DatetimeIndex(df['Order Date']).month
# df.head(10)
df['mm'] = pd.to_datetime(df['Order Date']).dt.month
df.head(10)

ParserError: Unknown string format: Order Date